CREATE SCHEMA IF NOT EXISTS validation_core;
CREATE SCHEMA IF NOT EXISTS validation_mart;

CREATE TABLE validation_core.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    insert_date_time TIMESTAMPTZ NOT NULL
);

CREATE TABLE validation_core.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_number TEXT NOT NULL,
    status TEXT NOT NULL,
    insert_date_time TIMESTAMPTZ NOT NULL
);

CREATE TABLE validation_mart.daily_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_date DATE NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    insert_date_time TIMESTAMPTZ NOT NULL
);

CREATE TABLE validation_mart.inventory_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT NOT NULL,
    quantity_on_hand INTEGER NOT NULL,
    insert_date_time TIMESTAMPTZ NOT NULL
);

INSERT INTO validation_core.orders (order_number, amount, insert_date_time)
VALUES
    ('ORD-1001', 129.90, NOW() - INTERVAL '45 minutes'),
    ('ORD-1002', 58.20, NOW() - INTERVAL '30 minutes'),
    ('ORD-1003', 211.00, NOW() - INTERVAL '15 minutes');

INSERT INTO validation_core.customers (customer_number, status, insert_date_time)
VALUES
    ('CUS-2001', 'active', NOW() - INTERVAL '2 hours'),
    ('CUS-2002', 'active', NOW() - INTERVAL '90 minutes'),
    ('CUS-2003', 'pending', NOW() - INTERVAL '1 hour');

INSERT INTO validation_mart.daily_sales (business_date, total_amount, insert_date_time)
VALUES
    (CURRENT_DATE - 2, 984.55, NOW() - INTERVAL '5 hours'),
    (CURRENT_DATE - 1, 1210.10, NOW() - INTERVAL '3 hours'),
    (CURRENT_DATE, 344.30, NOW() - INTERVAL '90 minutes');

INSERT INTO validation_mart.inventory_snapshot (sku, quantity_on_hand, insert_date_time)
VALUES
    ('SKU-1', 44, NOW() - INTERVAL '4 hours'),
    ('SKU-2', 12, NOW() - INTERVAL '2 hours'),
    ('SKU-3', 89, NOW() - INTERVAL '30 minutes');
